### ISSUE TITLE
Fallbacks and Conditional Css Tags

### ISSUE THREAD

**Issue by theperfectwill** [askupasoftware/wp-dynamic-css#6]
@ykadosh 

Thoughts on this? I was just thinking it over and looking at the css and there is no fallback or conditional tags. So looking forward it seems a little problematic at the moment to use WP Dynamic Css on a greater scale. 

For example...

``` css

/*
Examples...
*/

/* Default H1 Setting */

h1 {
    color: $default_font_color;
}

/* Single Post H1 Setting */
/* (if this is NOT set, how to fallback to the above default setting?) */

h1 {
    color: $post_font_color;
}

/* Single Post H1 Setting */
/* (if a post setting is NOT set AND no default settings are set how to return a default value? Or return nothing and empty the line of css?) */

h1 {
    color: $post_font_color;
}

/* If the above is not set then the below will print */
h1 {
    color: ;
}
```

I had some ideas and tried to make it simple. I think it should operate like php, so I was thinking something like this to make my point... and used HTML syntax since it would likely be familiar and a little easy on the eyes when writing the css. 

``` css

/*
Examples...
*/

/* Default H1 Setting */

h1 {
    color: <iftrue>$post_font_color</><else>$default_font_color</>;
}
h1 {
    color: <iftrue>$post_font_color</><elseif>$default_font_color</><else>#555</>;
}
```

Any ideas or feedback? How to go about this?

I only see one way which is to use php to find the option value then load the css file based on that value, but this can end up including a lot more css files than needed or user friendly. 

My thoughts **example**... 

If `$post_font_color` is **true** then...

``` php
wp_dynamic_css_enqueue('user-generated-styles', '/post-font-color.css');
```

If `$post_font_color` is **false** then...

``` php
wp_dynamic_css_enqueue('user-generated-styles', '/default-font-color.css');
```

But you can probably see how that can quickly become a lot of little css files when using multiple css properties for one css heading and others.
